apiVersion: v1
kind: Service
metadata:
  labels:
    fr.correctexam.service: back
  name: back
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    fr.correctexam.service: back
status:
  loadBalancer: {}
