apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: correctexam
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "10G"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
  namespace: correctexam
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 8080
      - path: /management
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 8080
      - path: /services
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 8080
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 8080
      - path: /v3/api-docs
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 8080
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 8080
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 8080
      - path: /maildev
        pathType: Prefix
        backend:
          service:
            name: maildev
            port:
              number: 1080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front
            port:
              number: 80

